config/routes.rb
Rails.application.routes.draw do
  # get "todos", to: "todos#index"

  # get "todos/:id", to: "todos#show"

  # post "todos", to: "todos#create"
  get "/" =>"home#index"

  resources :todos , :users

  get "/signin" => "sessions#new" , as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
    validates :todo_text, presence: true
    validates :due_date, presence: true
    validates :todo_text, length: {minimum: 2 }
    belongs_to :user

    def self.of_user(user)
        all.where(user_id: user.id)
    end


    def due_today?
        due_date == Date.today
    end

    def self.overdue
        all.where("due_date < ?", Date.today)
    end

    def self.due_today
        all.where("due_date = ?", Date.today)
    end

    def self.due_later
        all.where("due_date > ?", Date.today)
    end

    def self.completed
        all.where(completed: true)
    end

    def self.show_list
        puts "My Todo_list\n\n"
        puts "Overdue\n"
        puts overdue.show_list
        puts "\n\n"

        puts "Due Today\n"
        puts due_today.show_list
        puts "\n\n"

        puts "Due Later\n"
        puts due_later.show_list
        puts "\n\n"
    end

    def self.mark_as_complete!(id)
        todo = find(id)
        todo.completed = true
        todo.after_save :todo
    end
end 

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :todos


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :ensure_user_logged_in
    def ensure_user_logged_in
        unless current_user
            redirect_to "/"
        end
    end
    def current_user
        @current_user if @current_user
        current_user_id = session[:current_user_id]
        if current_user_id
            @current_user = User.find(current_user_id)
        else
            nil
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def index
        if current_user
            redirect_to todos_path
        else
            render "index"
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if(user && user.authenticate(params[:password]))
          session[:current_user_id] = user.id
          redirect_to todos_path
        else
          flash[:error] = "Your login attempt was invalid. Please retry."
          redirect_to new_sessions_path
        end
    end
    
    def destroy
        session[:current_user_id] = nil
        @current_user = nil
        redirect_to "/"
    end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    # skip_before_action :verify_authenticity_token
    def index
        @todos = Todo.of_user(current_user)
        render "index"
    end

    def show
        id = params[:id]
        todo = Todo.of_user(current_user).find(id)
        render plain: todo.to_pleasent_string
    end

    def create
        todo_text = params[:todo_text]
        due_date = params[:due_date]
        new_todo = Todo.new(
            todo_text: todo_text,
            due_date: due_date,
            completed: false,
            user_id: current_user.id,
       )
       if new_todo.save
        redirect_to todos_path
       else
        flash[:error] = new_todo.errors.full_messages.join(", ")
        redirect_to todos_path
       end

     end 

     def destroy
        id =params[:id]
        todo = Todo.of_user(current_user).find(id)
        todo.destroy
        redirect_to todos_path
     end

     def update 
        id = params[:id]
        completed = params[:completed]
        todo = Todo.of_user(current_user).find(id)
        todo.completed = completed
        todo.save!
        redirect_to todos_path
     end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :ensure_user_logged_in
    
    skip_before_action :verify_authenticity_token
    def new
        render "users/new"
    end

    def create
        User.create(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email],
            password: params[:password]
        )
        redirect_to "/"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
<h2>Welcome to To-Do Home Page</h2>

<h3>If New user, <%= link_to "Sign up here", new_user_path %></h3>

<h3>If Existing user, <%= link_to "Sign-in here", new_sessions_path %></h3>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
  </head>

  <body>
  <div>
  <% if @current_user%>
  <p class="userheader">
  Welcome <%= @current_user.first_name%>
  <%= link_to "Sign-Out", destroy_session_path, method: "delete"%>
  </p>
  <% end %>
</div>
  <% if flash[:error] %>
  <p class="Flash">
  <%= flash[:error] %>
  </p>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo_section.html.erb
   <div class="render">
   <h4><%=section_title%></h4>
   <small><%= todos.completed.count %>/<%= todos.count  %></small>
   <% todos.each do |todo| %>
   <div class="check">
   <%= form_with(url: "/todos/#{todo.id}", method:"put") do %>
   <input type="checkbox" 
   class="checkbox" 
   name="completed" <%= todo.completed ? "checked" : " " %>
   onclick="this.form.submit()"
   /> 
   <% end %>
   <%= todo.todo_text%>
   <% if show_due_date%>
   <small class="date"><%= todo.due_date.to_s(:short)%><small>
   <% end%>
   <%# <a href="javascript:void(0)" class="TodoItem-delete"> %>
   <%= form_with(url: "/todos/#{todo.id}", method:"delete") do %>
  <input type='image' src="trash-can-outline.png">
  <% end%>
   </div>
   <% end %>
   </div>

app/views/todos/index.html.erb
<div>
 <div class="container">
   <h2>My To-do List</h2>
   <%= form_with(url: "/todos", method:"post") do %>
   
   <input type="text" id="Todo" placeholder="What's next?" name="todo_text"/>
   <input type="date" id="date" name="due_date"/>
   <input type="submit" class="btn" value="Add" /><br/>
   
   <% end %>
</div>
<div>
<%= render partial: "todo_section",
 locals: {section_title:"Overdue",
 todos: @todos.overdue,
 show_due_date: true
 } 
 %>
</div>
<%= render partial: "todo_section",
 locals: {section_title:"Due Today",
 todos: @todos.due_today,
 show_due_date: false
 } 
 %>

<%= render partial: "todo_section",
 locals: {section_title:"Due Later",
 todos: @todos.due_later,
 show_due_date: true
 }
 %>
 </div>

app/views/users/new.html.erb
<section class = "sign-up-form">
  <%= form_with url: users_path do |form| %>
    <div class = "sign-up-field">
      <label> First Name </label>
      <%= form.text_field :first_name %>
    </div>
    
    <div class = "sign-up-field">
      <label> Last Name </label>
      <%= form.text_field :last_name %>
    </div>

    <div class = "sign-up-field">
      <label> Email </label>
      <%= form.email_field :email %>
    </div>

    <div class = "sign-up-field">
      <label> Password </label>
      <%= form.password_field :password %>
    </div>
    <%= form.submit "Sign-up!", class: "form-submit" %>
  <% end %>
</section>